### ISSUE TITLE
Non-root install

### ISSUE THREAD

**Issue by diegopaludo** [tioxy/panoptes#2]
Install via pip in user mode doesn't copy binary file.

**Comment by tioxy** [comment]
~~I was not able to replicate this error with Debian 9.~~

~~Panoptes will be moving how it's packaged from Disutils to Setuptools.~~
~~The project files restructure will be happening in the same release.~~

~~Meanwhile, there are three ways to solve it:~~

### ~~1. Installing as sudo~~
```sh
sudo -i pip install --upgrade panoptes
```

### ~~2. Running from the source~~
```sh
pip install --upgrade panoptes
git clone https://github.com/tioxy/panoptes.git
./panoptes/panoptesctl aws analyze --region YOUR-REGION
```

### ~~3. [NOT RECOMMENDED] Copying panoptesctl file manually~~
```sh
git clone https://github.com/tioxy/panoptes.git
sudo chmod +x ./panotptes/panoptesctl
sudo cp ./panoptes/panoptesctl /usr/bin/
```

~~Will be trying to make Panoptes installation available without requiring sudo.~~
~~Thank you!~~

**Comment by tioxy** [comment]
Panoptes 0.2.3 was released and this issue has been fixed.

You can run now:
```sh
pip install panoptes --upgrade --user
```

**Comment by tioxy** [comment]
Panoptes 0.2.3.0 was released and this issue has been fixed.

You can now run:
```sh
pip install panoptes --upgrade --user
```

**EDIT:** You may need to add inside your *~/.bashrc* the line below to add the script inside your PATH variable
```sh
PATH=$PATH:$HOME/.local/bin/
```
